app = "portfolio-backend"
primary_region = "iad"

[build]
  dockerfile = "Dockerfile"

[env]
  NODE_ENV = "production"
  PORT = "8080"
  NODE_OPTIONS = "--enable-source-maps --trace-uncaught --unhandled-rejections=strict"

[[services]]
  protocol = "tcp"
  internal_port = 8080

  [[services.ports]]
    handlers = ["http"]
    port = 80
  [[services.ports]]
    handlers = ["tls","http"]
    port = 443

  [[services.http_checks]]
    path = "/api/health"
    method = "get"
    interval = 10000
    timeout = 2000